## About the project

> This project aims to compare the speed of matrix multiplication with and without the NumPy library (the fundamental package for scientific computing with Python).

## Matrix multiplication without Numpy

In [1]:
X = [[1, 7, 3],
    [3, 5, 6],
    [6, 8, 9]]

Y = [[1, 1, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]

def matrix_dot_matrix(X, Y):
    if len(X[0]) != len(Y):
        print("The number of columns in the first matrix doesn't match the number of rows in the second matrix. Multiplication is impossible.")
        return []
    else:
        output_matrix = []
        for i in range(len(X)):
            output_matrix.append([0] * len(Y[0]))
        for i in range(len(X)):
            for j in range(len(Y[0])):
                for k in range(len(Y)):
                    output_matrix[i][j] += X[i][k] * Y[k][j]
    return output_matrix

for part in matrix_dot_matrix(X, Y):
    print(part)

[55, 65, 49, 5]
[57, 68, 72, 12]
[90, 107, 111, 21]


## Matrix multiplication with NumPy

In [2]:
X = [[1, 7, 3],
    [3, 5, 6],
    [6, 8, 9]]

Y = [[1, 1, 1, 2],
   [6, 7, 3, 0],
   [4, 5, 9, 1]]

import numpy as np
print(np.dot(X,Y))

[[ 55  65  49   5]
 [ 57  68  72  12]
 [ 90 107 111  21]]


## Speed comparison: which operation takes less time?

In [3]:
#Matrix multiplication without Numpy

X = []
for i in range(200):
    X.append([12126273] * 200)

Y = []
for i in range(200):
    Y.append([1212627367] * 100)

from datetime import datetime
import time
start_time_1 = datetime.now()

def matrix_dot_matrix(X, Y):
    if len(X[0]) != len(Y):
        print("The number of columns in the first matrix doesn't match the number of rows in the second matrix. Multiplication is impossible.")
        return []
    else:
        output_matrix = []
        for i in range(len(X)):
            output_matrix.append([0] * len(Y[0]))
        for i in range(len(X)):
            for j in range(len(Y[0])):
                for k in range(len(Y)):
                    output_matrix[i][j] += X[i][k] * Y[k][j]
    return output_matrix

matrix_dot_matrix(X, Y)

print(datetime.now() - start_time_1)

0:00:01.059259


In [4]:
#Matrix multiplication with NumPy

X = []
for i in range(200):
    X.append([12126273] * 200)

Y = []
for i in range(200):
    Y.append([1212627367] * 100)

from datetime import datetime
import time
start_time_2 = datetime.now()

import numpy as np
np.dot(X,Y)

print(datetime.now() - start_time_2)

0:00:00.007759


> As a result, we found out that NumPy performs matrix multiplication much faster than just Python.